INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('América', 42215000, 1, null, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Ásia', 44482000, 1, null, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Europa', 10360000, 1, null, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Oceania', 8480000, 1, null, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('África', 30230000, 1, null, 'a');

INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Europa Meridional', 1294920, 2, 3, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Ásia Ocidental', 18253927, 2, 2, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Ásia Meridional', 6400127, 2, 2, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('América Latina e Caribe', 20139378, 2, 1, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Europa Ocidental', 1084793, 2, 3, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Austrália e Nova Zelândia', 7945610, 2, 4, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Europa Oriental', 6277869, 2, 3, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Sudeste da Ásia', 4340700, 2, 2, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Ásia Oriental', 11560456, 2, 2, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Europa Setentrional', 1702418, 2, 3, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Melanésia', 529590, 2, 4, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Micronésia', 3170, 2, 4, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Ásia Central', 3926790, 2, 2, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Polinésia', 8090, 2, 4, 'a');

INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('América do Norte', 24709000, 3, 1, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Caribe', 239681, 3, 9, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('América Central', 742204, 3, 9, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('América do Sul', 17850568, 3, 9, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('África Central', 6496820, 3, 5, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('África Setentrional', 7769438, 3, 5, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('África Ocidental', 6064060, 3, 5, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('África Oriental', 6667493, 3, 5, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('África Meridional', 2650670, 3, 5, 'a');

INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Andorra', 468, 4, 6, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Emirados Árabes Unidos', 83600, 4, 7, 'os');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Afeganistão', 652230, 4, 8, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Antígua e Barbuda', 443, 4, 21, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Albânia', 28748, 4, 6, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Armênia', 29743, 4, 7, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Angola', 1246700, 4, 24, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Argentina', 2780400, 4, 23, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Áustria', 83871, 4, 10, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Austrália', 7741220, 4, 11, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Azerbaijão', 86600, 4, 7, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Bósnia e Herzegovina', 51197, 4, 6, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Barbados', 430, 4, 21, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Bangladesh', 148460, 4, 8, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Bélgica', 30528, 4, 10, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Burkina Faso', 274200, 4, 26, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Bulgária', 110879, 4, 12, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Barein', 760, 4, 7, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Burundi', 27830, 4, 27, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Benin', 112622, 4, 26, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Brunei', 5765, 4, 13, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Estado Plurinacional da Bolívia', 1098581, 4, 23, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Brasil', 8510346, 4, 23, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Bahamas', 13880, 4, 21, 'as');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Butão', 38394, 4, 8, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Botsuana', 581730, 4, 28, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Belarus', 207600, 4, 12, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Belize', 22966, 4, 22, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Canadá', 9984670, 4, 20, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('República Democrática do Congo', 2344858, 4, 24, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('República Centro-Africana', 622984, 4, 24, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Congo', 342000, 4, 24, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Suíça', 41277, 4, 10, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Costa do Marfim', 322463, 4, 26, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Chile', 756102, 4, 23, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Camarões', 475440, 4, 24, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('China', 9596960, 4, 14, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Colômbia', 1138910, 4, 23, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Costa Rica', 51100, 4, 22, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Cuba', 110860, 4, 21, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Cabo Verde', 4033, 4, 26, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Chipre', 9251, 4, 7, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('República Tcheca', 78867, 4, 12, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Alemanha', 357022, 4, 10, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Djibouti', 23200, 4, 27, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Dinamarca', 43094, 4, 15, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Dominica', 751, 4, 21, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('República Dominicana', 48670, 4, 21, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Argélia', 2381741, 4, 25, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Equador', 283561, 4, 23, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Estônia', 45228, 4, 15, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Egito', 1001450, 4, 25, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Eritreia', 117600, 4, 27, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Espanha', 505370, 4, 6, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Etiópia', 1104300, 4, 27, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Finlândia', 338145, 4, 15, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Fiji', 18274, 4, 16, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Estados Federados da Micronésia', 702, 4, 17, 'os');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('França', 643801, 4, 10, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Gabão', 267667, 4, 24, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Reino Unido da Grã-Bretanha e Irlanda do Norte', 243610, 4, 15, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Granada', 344, 4, 21, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Geórgia', 69700, 4, 7, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Gana', 238533, 4, 26, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Gâmbia', 11300, 4, 26, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Guiné', 245857, 4, 26, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Guiné Equatorial', 28051, 4, 24, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Grécia', 131957, 4, 6, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Guatemala', 108889, 4, 22, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Guiné-Bissau', 36125, 4, 26, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Guiana', 214969, 4, 23, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Honduras', 112090, 4, 22, 'as');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Croácia', 56594, 4, 6, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Haiti', 27750, 4, 21, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Hungria', 93028, 4, 12, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Indonésia', 1904569, 4, 13, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Irlanda', 70273, 4, 15, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Israel', 20770, 4, 7, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Índia', 3287263, 4, 8, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Iraque', 438317, 4, 7, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('República Islâmica do Irã', 1648195, 4, 8, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Islândia', 103000, 4, 15, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Itália', 301340, 4, 6, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Jamaica', 10991, 4, 21, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Jordânia', 89342, 4, 7, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Japão', 377915, 4, 14, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Quênia', 580367, 4, 27, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Quirguistão', 199951, 4, 18, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Camboja', 181035, 4, 13, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Kiribati', 811, 4, 17, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Comores', 2235, 4, 27, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('São Cristóvão e Nevis', 261, 4, 21, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('República Popular Democrática da Coreia', 120538, 4, 14, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('República da Coreia', 99720, 4, 14, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Kuwait', 17818, 4, 7, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Cazaquistão', 2724900, 4, 18, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('República Democrática Popular do Laos', 236800, 4, 13, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Líbano', 10400, 4, 7, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Santa Lúcia', 616, 4, 21, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Liechtenstein', 160, 4, 10, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Sri Lanka', 65610, 4, 8, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Libéria', 111369, 4, 26, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Lesoto', 30355, 4, 28, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Lituânia', 65300, 4, 15, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Luxemburgo', 2586, 4, 10, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Letônia', 64589, 4, 15, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Líbia', 1759540, 4, 25, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Marrocos', 446550, 4, 25, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Mônaco', 2, 4, 10, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('República da Moldávia', 33851, 4, 12, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Montenegro', 13812, 4, 6, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Madagascar', 587041, 4, 27, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Ilhas Marshall', 181, 4, 17, 'as');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Macedônia do Norte', 25713, 4, 6, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Mali', 1240192, 4, 26, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Mianmar', 676578, 4, 13, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Mongólia', 1564116, 4, 14, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Mauritânia', 1030700, 4, 26, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Malta', 316, 4, 6, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Maurício', 2040, 4, 27, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Maldivas', 298, 4, 8, 'as');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Malauí', 118484, 4, 27, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('México', 1964375, 4, 22, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Malásia', 329847, 4, 13, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Moçambique', 799380, 4, 27, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Namíbia', 824292, 4, 28, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Niger', 1267000, 4, 26, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Nigéria', 923768, 4, 26, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Nicarágua', 130370, 4, 22, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Holanda', 41543, 4, 10, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Noruega', 323802, 4, 15, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Nepal', 147181, 4, 8, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Nauru', 21, 4, 17, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Nova Zelândia', 268838, 4, 11, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Omã', 309500, 4, 7, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Panamá', 75420, 4, 22, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Peru', 1285216, 4, 23, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Papua Nova Guiné', 462840, 4, 16, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Filipinas', 300000, 4, 13, 'as');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Paquistão', 796095, 4, 8, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Polônia', 312685, 4, 12, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Portugal', 92090, 4, 6, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Palau', 459, 4, 17, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Paraguai', 406752, 4, 23, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Catar', 11586, 4, 7, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Romênia', 238391, 4, 12, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Sérvia', 77474, 4, 6, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Federação da Rússia', 17098242, 4, 12, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Ruanda', 26338, 4, 27, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Arábia Saudita', 2149690, 4, 7, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Ilhas Salomão', 28896, 4, 16, 'as');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Seichelles', 455, 4, 27, 'as');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Sudão', 1861484, 4, 25, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Suécia', 450295, 4, 15, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Singapura', 719, 4, 13, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Eslovênia', 20273, 4, 6, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Eslováquia', 49035, 4, 12, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Serra Leoa', 71740, 4, 26, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('San Marino', 61, 4, 6, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Senegal', 196722, 4, 26, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Somália', 637657, 4, 27, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Suriname', 163820, 4, 23, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Sudão do Sul', 644329, 4, 27, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('São Tomé e Príncipe', 964, 4, 24, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('El Salvador', 21041, 4, 22, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Síria', 185180, 4, 7, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Eswatini', 17360, 4, 28, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Chade', 1284000, 4, 24, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Togo', 56785, 4, 26, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Tailândia', 513120, 4, 13, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Tadjiquistão', 144100, 4, 18, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Timor-Leste', 14874, 4, 13, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Turcomenistão', 488100, 4, 18, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Tunísia', 163610, 4, 25, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Tonga', 747, 4, 19, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Turquia', 783562, 4, 7, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Trinidad e Tobago', 5128, 4, 21, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Tuvalu', 26, 4, 19, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('República Unida da Tanzânia', 947300, 4, 27, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Ucrânia', 603550, 4, 12, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Uganda', 241038, 4, 27, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Estados Unidos da América', 9833517, 4, 20, 'os');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Uruguai', 176215, 4, 23, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Uzbequistão', 447400, 4, 18, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('São Vicente e Granadinas', 389, 4, 21, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('República Bolivariana da Venezuela', 912050, 4, 23, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Vietnã', 331210, 4, 13, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Vanuatu', 12189, 4, 16, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Samoa', 2831, 4, 19, '');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Iêmen', 527968, 4, 7, 'o');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('África do Sul', 1219090, 4, 28, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Zâmbia', 752618, 4, 27, 'a');
INSERT INTO Regiao(nome, tamanho, id_tipo_regiao, id_regiao_pai, artigo) VALUES ('Zimbábue', 390757, 4, 27, 'o');
