INSERT inTO TipoEnergia VALUES('Nuclear', 'Energia gerada a partir de usinas nucleares')
INSERT inTO TipoEnergia VALUES('Eólica',  'Energia gerada a partir dos ventos')
INSERT inTO TipoEnergia VALUES('Solar', 'Energia gerada a partir de placas solares que capturam a luz do sol')
INSERT inTO TipoEnergia VALUES('Hidrelétrica', 'Energia gerada a partir das correntes da água')
INSERT inTO TipoEnergia VALUES('Biomassa', 'Energia gerada a partir da queima de matérias orgânicas')
INSERT inTO TipoEnergia VALUES('Combustíveis Fósseis', 'Energia gerada a partir da queima de materiais derivados de petróleo')
